// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MulhollandRealEstate.API.Data;

#nullable disable

namespace MulhollandRealEstate.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414194101_AddEmployeeAuthAndSkills")]
    partial class AddEmployeeAuthAndSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MulhollandRealEstate.API.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("full_name");

                    b.Property<string>("HomePropertyId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("home_property_id");

                    b.Property<int>("MaxOpenTickets")
                        .HasColumnType("int")
                        .HasColumnName("max_open_tickets");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_employees_username");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("MulhollandRealEstate.API.Models.EmployeeSkill", b =>
                {
                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<string>("Skill")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("skill");

                    b.HasKey("EmployeeId", "Skill");

                    b.HasIndex("Skill")
                        .HasDatabaseName("ix_employee_skills_skill");

                    b.ToTable("employee_skills", (string)null);
                });

            modelBuilder.Entity("MulhollandRealEstate.API.Models.MaintenanceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("actual_category");

                    b.Property<string>("ActualUrgency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("actual_urgency");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at");

                    b.Property<long?>("AssignedEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_employee_id");

                    b.Property<string>("AssignmentSource")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("assignment_source");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("building_type");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("closed_by");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("confidence_score");

                    b.Property<bool>("HasImage")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_image");

                    b.Property<string>("ImageSeverityHint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("image_severity_hint");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("image_type");

                    b.Property<string>("ImageUrlOrCount")
                        .HasColumnType("longtext")
                        .HasColumnName("image_url_or_count");

                    b.Property<DateTime?>("LastTriagedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_triaged_at");

                    b.Property<bool>("NeedsHumanReview")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("needs_human_review");

                    b.Property<string>("PredictedCategory")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("predicted_category");

                    b.Property<string>("PredictedUrgency")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("predicted_urgency");

                    b.Property<int>("PriorRequestsLast6Mo")
                        .HasColumnType("int")
                        .HasColumnName("prior_requests_last_6mo");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("property_id");

                    b.Property<int>("RequestNumber")
                        .HasColumnType("int")
                        .HasColumnName("request_number");

                    b.Property<string>("RequestText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("request_text");

                    b.Property<DateTime>("RequestTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("request_timestamp");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("resolution_notes");

                    b.Property<string>("RiskNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("risk_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionChannel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("submission_channel");

                    b.Property<string>("TagsJson")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("tags_json");

                    b.Property<int>("TenantTenureMonths")
                        .HasColumnType("int")
                        .HasColumnName("tenant_tenure_months");

                    b.Property<string>("TriageSource")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("triage_source");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("unit_number");

                    b.HasKey("Id");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_maintenance_requests_request_number");

                    b.ToTable("maintenance_requests", (string)null);
                });

            modelBuilder.Entity("MulhollandRealEstate.API.Models.MaintenanceRequestEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("actor");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("details_json");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("event_timestamp");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("event_type");

                    b.Property<long>("MaintenanceRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("maintenance_request_id");

                    b.HasKey("Id");

                    b.ToTable("maintenance_request_events", (string)null);
                });

            modelBuilder.Entity("MulhollandRealEstate.API.Models.MaintenanceRequestImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)")
                        .HasColumnName("file_name");

                    b.Property<long>("MaintenanceRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("maintenance_request_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceRequestId")
                        .HasDatabaseName("ix_mri_request");

                    b.ToTable("maintenance_request_images", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
